
spring:
  application:
    name: WEBSOCKET
  profiles:
    active:
      - dev
  redis:
    password: test
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

logging:
  file:
    name: src/main/resources/script/stage_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true

app:
  auth:
    access-token:
      path: ${ACCESS_TOKEN_KEY_PATH}
    refresh-token:
      path: ${REFRESH_TOKEN_KEY_PATH}

grpc:
  client:
    grpc-discord-service:
      address: static://localhost:8800
      negotiationType: plaintext