
spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
      - dev

logging:
  file:
    name: src/main/resources/script/stage_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true