
spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
      - dev
  redis:
    password: test
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

logging:
  file:
    name: src/main/resources/script/stage_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true