
spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
      - dev
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: userTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  file:
    name: src/main/resources/script/stage_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true