
grpc:
  server:
    port: 8800

spring:
#  datasource:
#    url: jdbc:h2:mem:ecommerce_dev_db;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
##    url: jdbc:h2:file:./data/sample;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;NON_KEYWORDS=USER
#    username: sa
#    password:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 5000
      max-lifetime: 1800000
      pool-name: mystery-pool
#      jdbc-url: jdbc:h2:mem:lotte_dev_db;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql';MODE=MySQL
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/discord_service

      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  sql:
    init:
      schema-locations: classpath:schema.sql # run schema.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        web: DEBUG
#        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
#    com.zaxxer.hikari: TRACE
#    com.zaxxer.hikari.HikariConfig: DEBUG