
server:
  servlet:
    context-path: /app

spring:
  application:
    name: PROXY-CLIENT
  profiles:
    active:
      - dev
  redis:
    password: test
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

logging:
  file:
    name: src/main/resources/script/stage_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.lettuce: DEBUG

app:
  auth:
    access-token:
      path: ${ACCESS_TOKEN_KEY_PATH}
    refresh-token:
      path: ${REFRESH_TOKEN_KEY_PATH}